"""Tool prompt: tool_system — injected into system context when tools are enabled."""


def tool_system_prompt(tool_schema: str) -> str:
    """Return the tool-calling system instructions with the current tool schema embedded.

    Args:
        tool_schema: JSON string generated by ``ToolRegistry.get_schema_json()``.
                     Contains the full list of available tools and their argument schemas.

    Returns:
        Formatted system prompt string.
    """
    return f"""\
## Tool-Calling Instructions

You have access to the following tools. When you want to create, edit, or manage files, \
you MUST use a tool — do NOT just print the file content as prose.

### When to use tools
- Use `create_file` to write a new file or completely overwrite one.
- Use `edit_file` to make a targeted change within an existing file.
- Use `read_file` before editing a file you haven't seen yet in this session.
- Use `generate_diff` / `preview_diff` to show proposed changes before writing.
- Use `git_commit` after you finish writing/editing a set of related files.
- Use `create_folder` to organise files into subdirectories.

### Available tools
{tool_schema}

### Rules
1. Call only ONE tool per response turn.
2. After a tool result is returned, you may call another tool or continue with prose.
3. Never invent tool names not listed above.
4. Always use relative paths (relative to the workspace root).
"""
